/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame1.java
 *
 * Created on Jul 3, 2013, 11:02:21 AM
 */
package com.ipi.ekata;

/**
 *
 * @author glassfish
 */
public class Frame1 extends javax.swing.JFrame {

    /** Creates new form Frame1 */
    public Frame1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        text2 = new javax.swing.JTextArea();
        btnAlih = new javax.swing.JButton();
        btnBarasihi = new javax.swing.JButton();
        btnBulikakan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text1.setColumns(20);
        text1.setRows(5);
        jScrollPane1.setViewportView(text1);

        text2.setColumns(20);
        text2.setRows(5);
        jScrollPane2.setViewportView(text2);

        btnAlih.setText("Alih");
        btnAlih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlihActionPerformed(evt);
            }
        });

        btnBarasihi.setText("Barasihi");
        btnBarasihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarasihiActionPerformed(evt);
            }
        });

        btnBulikakan.setText("Bulikakan");
        btnBulikakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBulikakanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBarasihi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBulikakan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlih)
                    .addComponent(btnBarasihi)
                    .addComponent(btnBulikakan))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlihActionPerformed
        String awal = text1.getText().toUpperCase();
        StringBuffer sb = new StringBuffer();
        
        for (char c : awal.toCharArray()){
            int o = (int) c;
            sb.append(convert(o));
        }
        
        text2.setText(sb.toString());
        
    }//GEN-LAST:event_btnAlihActionPerformed

    private void btnBarasihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarasihiActionPerformed
        text1.setText(null);
        text2.setText(null);
    }//GEN-LAST:event_btnBarasihiActionPerformed

    private void btnBulikakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBulikakanActionPerformed
        String awal = text2.getText().toUpperCase();
        StringBuffer sb = new StringBuffer();
        
        for (char c : awal.toCharArray()){
            int o = (int) c;
            sb.append(unconvert(o));
        }
        
        text1.setText(sb.toString());
        
    }//GEN-LAST:event_btnBulikakanActionPerformed

    public char convert(int c){
        c = c + 4;
        return (char) c;
    }
    
    public char unconvert(int c){
        c = c - 4;
        return (char) c;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlih;
    private javax.swing.JButton btnBarasihi;
    private javax.swing.JButton btnBulikakan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea text1;
    private javax.swing.JTextArea text2;
    // End of variables declaration//GEN-END:variables
}
